name: meedu
description: A simple State Managment, Dependency Injection, Reactive programming for dart Projects.
version: 4.1.0
homepage: https://github.com/darwin-morocho/flutter-meedu/tree/master/packages/meedu
documentation: https://flutter.meedu.app

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta: ^1.3.0


dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  # flutter:
  #   sdk: flutter
  coverage: ^1.0.1
  test: ^1.16.5
  equatable: ^2.0.0
  pedantic: ^1.11.0
